name: Essentials
author: ZalgoDev
authors:
  - Contributors
version: 0.1.0
api: 5.0.0
main: ZalgoDev\Essentials\Main
src-namespace-prefix: ZalgoDev\Essentials
permissions:
  essentials.fly:
    description: Allow players to use command /fly
    default: op
  essentials.fly.others:
    description: Allow players to use command /fly <player>
    default: op
  essentials.vanish:
    description: Allow players to use command /vanish
    default: op
  essentials.vanish.others:
    description: Allow players to use command /vanish <player>
    default: op
  essentials.gm:
    description: Allow players to use command /gm
    default: op
  essentials.gm.others:
    description: Allow players to use command /gm <player>
    default: op