name: Essentials
author: ZalgoDev
authors:
  - Contributors
version: 0.0.1
api: 5.0.0
main: ZalgoDev\Essentials\Main
src-namespace-prefix: ZalgoDev\Essentials
commands:
  fly:
    description: Toggle flight mode for yourself or another player
    permission: essentials.fly
    permission-message: "You don't have permission to use this command."
    aliases:
      - f
    usage: /fly [player]
permissions:
  essentials.fly:
    description: Allow players to toggle flight mode
    default: op
  essentials.fly.other:
    description: Allow players to toggle flight mode for others
    default: op
